### ISSUE TITLE
value = \"a.link/0 - What does it mean or what does it refer to? 

### ISSUE THREAD

**Issue by sakunix** [rocklabs-io/ic-nft#10]
"`value = \"a.link/0`" What does it mean or what does it refer to? in

`dfx canister --no-wallet call token_ERC721 mint "'($ALICE_PUBLIC_KEY, record { filetype = \"jpg\"; location = variant {IPFS = \"hash0\"}; attributes = vec {record {key = \"url\"; value = \"a.link/0\"}}})'"`

thank @ccyanxyz

**Comment by sakunix** [comment]
![imagen](https://user-images.githubusercontent.com/22086570/150632370-bfac32d9-0b60-402e-9ed4-032be4b0d17d.png)

**Comment by ccyanxyz** [comment]
it's just a placeholder value showcase how to use the `attributes`

**Comment by ccyanxyz** [comment]
try:
dfx canister --no-wallet call token_ERC721 mint "'($ALICE_PUBLIC_KEY, opt record { filetype = \"jpg\"; location = variant {IPFS = \"hash0\"}; attributes = vec {record {key = \"url\"; value = \"a.link/0\"}}})'"

**Comment by sakunix** [comment]
> 

thank @ccyanxyz  I hope this means the mint was done correctly 

![imagen](https://user-images.githubusercontent.com/22086570/150635436-a0d386e1-cebd-42eb-b2c7-27e552e922bd.png)

**Comment by ccyanxyz** [comment]
Yes it's correct.
