### ISSUE TITLE
source code don't compile

### ISSUE THREAD

**Issue by aakh1361** [rocklabs-io/ic-nft#11]
hi
i use ubuntu 21.04 and last version dfx 18.4
when i try compile show me error
This is the output of the commands

**********************************************************
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
**********************************************************
output :
info: Executing dfx install script, commit: ae3ec519c56649608f9015b65c8f29494f87076d
warn: Not forcing TLS v1.2, this is potentially less secure
info: Version found: 0.8.4
info: Creating uninstall script in ~/.cache/dfinity
info: uninstall path=/home/aakh1361/.cache/dfinity/uninstall.sh
info: Checking for latest release...
warn: Not forcing TLS v1.2, this is potentially less secure

Will install in: /home/aakh1361/bin
info: Installed /home/aakh1361/bin/dfx

**********************************************************
dfx start --background
**********************************************************
output :
Starting webserver for /_/
binding to: 127.0.0.1:35565
Feb 13 11:54:26.917 INFO ic-starter. Configuration: ValidatedConfig { replica_path: Some("/home/aakh1361/.cache/dfinity/versions/0.8.4/replica"), replica_version: "0.8.0", log_level: Warning, cargo_bin: "cargo", cargo_opts: "", state_dir: "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state", http_listen_addr: 127.0.0.1:0, http_port_file: Some("/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/replica-configuration/replica-1.port"), metrics_addr: None, provisional_whitelist: Some(All), artifact_pool_dir: "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/node-100/ic_consensus_pool", crypto_root: "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/node-100/crypto", state_manager_root: "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/node-100/state", registry_local_store_path: "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/ic_registry_local_store", unit_delay: None, initial_notary_delay: Some(600ms), detect_consensus_starvation: None, consensus_pool_backend: Some("rocksdb"), state_dir_holder: None }, Application: starter
Feb 13 11:54:26.917 INFO Initialize replica configuration "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/ic.json5", Application: starter
Feb 13 11:54:27.526 INFO Executing "/home/aakh1361/.cache/dfinity/versions/0.8.4/replica" "--replica-version" "0.8.0" "--config-file" "/home/aakh1361/Desktop/ICP/NFT_DEMO (1)/ic-nft-main/motoko/.dfx/state/replicated_state/ic.json5", Application: starter
Feb 13 11:54:29.374 WARN s:xyyjp-7ezpe-oevzf-dylwo-b4qqf-kydvp-q3yya-csfhi-sodaa-entha-xae/n:ea4tb-iqkxc-a5k7a-rh6nu-pc4mo-rkbqo-eobst-ley7x-gydfw-io7qv-gqe/ic_p2p/download_management PeerManagerImpl::new(): relay_config = None
version: 0.7.0
 Feb 13 03:54:29.426 INFO Log Level: INFO
 Feb 13 03:54:29.427 INFO Starting server. Listening on http://127.0.0.1:8000/

**********************************************************
dfx canister create --all
**********************************************************
output :
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Creating canister "nft"...
"nft" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "sale"...
"sale" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"

**********************************************************
dfx build
**********************************************************
output :
Building canisters...

**********************************************************
dfx canister install token --argument="(\"Test NFT\", \"TEST\", \"Test NFT collection\", principal \"4qehi-lqyo6-afz4c-hwqwo-lubfi-4evgk-5vrn5-rldx2-lheha-xs7a4-gae\")"
**********************************************************
output :
Cannot find canister id. Please issue 'dfx canister create token'.

**Comment by ccyanxyz** [comment]
You need to create the `token` canister first
