### ISSUE TITLE
confused about the type of metadata

### ISSUE THREAD

**Issue by GaoCan702** [rocklabs-io/ic-nft#17]
I have some confused about the option type of metadata in tokenInfo, allow to mint a nft without metadata?

**Comment by ccyanxyz** [comment]
Yes, this is to allow you to mint a token first, reveal the metadata later

**Comment by GaoCan702** [comment]
> maybe it's not necessary  to complete it in two steps (i am not sure)

**Comment by ccyanxyz** [comment]
Just provide the option, you can also mint the token with metadata.
